# Докер компоуз файл для работы с кодом из этого репозитория 
# (контейнеры не скачиваются с DockerHub)

services:
  db:
    image: postgres:16
    container_name: zakupki_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zakupki
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: zakupki_backend
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/zakupki"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build: ./frontend
    container_name: zakupki_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8000"
    depends_on:
      - backend
    command: npm run dev

volumes:
  pgdata: